# Generated by Django 3.1 on 2020-08-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0004_pessoa_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=6)),
                ('descricao', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='depto_atual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='aplicacao.departamento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='hist_deptos',
            field=models.ManyToManyField(related_name='hist_pessoa_depto', to='aplicacao.Departamento'),
        ),
    ]
