# Generated by Django 3.1 on 2020-09-13 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0006_pessoa_depto_chefia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='depto_chefia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='chefia_dpto', to='aplicacao.departamento'),
        ),
    ]
