# Generated by Django 3.1 on 2020-09-14 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0007_auto_20200913_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('modelo', models.CharField(max_length=30)),
                ('fabricacao', models.IntegerField(null=True)),
                ('proprietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='aplicacao.pessoa')),
            ],
        ),
    ]
