# Generated by Django 3.1 on 2020-09-14 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0008_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.IntegerField(null=True)),
                ('numero', models.IntegerField(null=True)),
                ('tipo', models.CharField(choices=[('P', 'Pessoal'), ('C', 'Comercial'), ('I', 'Indefinido')], default='I', max_length=1)),
                ('proprietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='aplicacao.pessoa')),
            ],
        ),
    ]
